spring.application.name=demoWechat


spring.mail.host=smtp.qq.com
spring.mail.username=766460679@qq.com
spring.mail.password=gpuubtttlryvbfce
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

